---
- name: EOrchestra, frestq python packages
  sudo: true
  sudo_user: eorchestra
  pip: virtualenv=/home/eorchestra/venv state=present
       requirements=/home/eorchestra/frestq/requirements.txt

- name: EOrchestra, eorchestra python packages
  sudo: true
  sudo_user: eorchestra
  pip: virtualenv=/home/eorchestra/venv state=present
       requirements=/home/eorchestra/election-orchestra/requirements.txt
